### ISSUE TITLE
Compatible with other Laptops?

### ISSUE THREAD

**Issue by vectorprogrammer** [Exodia-OS/exodia-acer-predator-ISO#2]
I wanted to try Exodia OS Acer-Predator edition however I am worried about the Compatibility issues. Can this Exodia OS run on DELL XPS 13 9343?

**Comment by mmsaeed509** [comment]
The **Acer Predator** Edition is similar to the **Home** Edition, with the only difference being that the Acer Predator Edition comes with `Predator-Sense-CLI` and `Predator-Sense-GUI` pre-installed to control RGB and fan speed for Acer Predator laptops.
